#!/bin/bash

unset GOBIN GOROOT GOARCH GOARM GOMAXPROCS
# get the bash script directory
d="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export GOPATH="$d"
echo "GOPATH=$GOPATH"

export PATH="$d/bin:$PATH"
echo "PATH=$PATH"

#export TMPDIR="$d/tmp"
#export TMPDIR="/tmp"
#echo "TMPDIR=$TMPDIR"

#export GOMAXPROCS=4
#echo "GOMAXPROCS=$GOMAXPROCS"

#export GOTRACEBACK=crash
#echo "GOTRACEBACK=$GOTRACEBACK"
